Repository ygowthamr/WhitePaper, pull requests merged in 2025-02, with the labels that each got.

#73 Update README.md
  README.md
Labels: IWOC2025, Easy

#72 Fix Issue #54: Added the login/signup via github oauth feature in new UI
  MyNotepad/settings.py
  MyNotepad/urls.py
  accounts/urls.py
  static/css/style.css
  templates/notesapp/login.html
  templates/notesapp/signup.html
Labels: IWOC2025, Hard

#77 Updated the readme and requirements file
  README.md
  requirements.txt
Labels: IWOC2025, Easy

#78 Note Sharing Functionality
  notes/urls.py
  notes/views.py
  static/javascript/authenticated.js
  templates/notesapp/main.html
  templates/notesapp/shared_note.html
Labels: SWOC, ADVANCE, IWOC2025, Hard

#83 Fix Issue #76: Styled the tags according to theme.
  MyNotepad/settings.py
  templates/notesapp/main.html
Labels: IWOC2025, Medium

#79 Added the toogle functionality
  static/css/NewStyle.css
  static/javascript/Theme.js
  templates/notesapp/index.html
  templates/notesapp/login.html
  templates/notesapp/main.html
  templates/notesapp/password_reset.html
  templates/notesapp/reset_password.html
  templates/notesapp/signup.html
Labels: IWOC2025, Hard

#84 Done with the notes card ui problem
  static/javascript/script.js
  templates/notesapp/main.html
Labels: IWOC2025, Hard

#92 Fix Issue #90: Minor UI update
  templates/notesapp/main.html
Labels: IWOC2025, Easy

#87 Added the Text Editor
  static/javascript/authenticated.js
  templates/notesapp/index.html
  templates/notesapp/main.html
Labels: IWOC2025, Hard

#98 Fix issue #89 : Added copy to clipboard feature
  MyNotepad/settings.py
  static/javascript/authenticated.js
Labels: IWOC2025, Medium

#101 Home Page Works Fine
  static/javascript/script.js
  templates/notesapp/index.html
Labels: IWOC2025, Hard

#102 Add Project Structure to README
  README.md
Labels: IWOC2025, Easy

#119 Done AI ChantBot, Image Functionalty, Share Via Short URL & QR Code , Vedio Functionality
  static/javascript/authenticated.js
  templates/notesapp/main.html
  templates/notesapp/shared_note.html
Labels: IWOC2025, Hard

#125 Add Animated Scroll-to-Top Button Across All Pages.
  index.html
  static/css/NewStyle.css
  static/javascript/script.js
Labels: SWOC, INTERMEDIATE, IWOC2025, Medium
