Repository ygowthamr/WhitePaper, pull requests merged in 2025-01, with the labels that each got.

#8 Made notepad logo clickable from every possible page
  templates/notesapp/login.html
  templates/notesapp/main.html
  templates/notesapp/signup.html
Labels: SWOC, INTERMEDIATE

#13 Prevent Empty Note Creation in Notepad Form
  static/javascript/script.js
  templates/notesapp/main.html
Labels: SWOC, BEGINNER

#14 fix issue #3: Add It Button Functionality on Index Page
  static/javascript/script.js
  templates/notesapp/index.html
Labels: SWOC, INTERMEDIATE

#20 Change Route of Login Link on Signup Page #5 #12
  templates/notesapp/signup.html
Labels: SWOC, BEGINNER

#26 fix issue #19: ADD form Validation
  accounts/views.py
  static/javascript/script.js
  templates/notesapp/login.html
  templates/notesapp/signup.html
Labels: SWOC, INTERMEDIATE

#27 Add "Scroll to Top" Button for Notes Page after login #11
  static/css/style.css
  static/images/scroll-top.png
  static/javascript/script.js
  templates/notesapp/main.html
Labels: SWOC, INTERMEDIATE

#32 Update README.md
  README.md
Labels: SWOC, BEGINNER

#34 #33 Fix: Add setuptools dependency to resolve distutils issue in Python 3.12.8
  requirements.txt
Labels: SWOC, INTERMEDIATE

#35 Added the simple footer #29
  static/css/style.css
  templates/notesapp/index.html
  templates/notesapp/login.html
  templates/notesapp/main.html
  templates/notesapp/signup.html
Labels: SWOC, INTERMEDIATE

#41 #17 Add sessions in app
  MyNotepad/middleware.py
  MyNotepad/settings.py
  accounts/urls.py
  accounts/views.py
  notes/views.py
  notesapp/views.py
  static/javascript/script.js
  templates/notesapp/main.html
Labels: SWOC, ADVANCE

#42 Issue-#39_Added sorting feature
  static/javascript/script.js
  templates/notesapp/index.html
Labels: SWOC, ADVANCE

#50 #45 Notes are now saved in database.
  accounts/urls.py
  accounts/views.py
  notes/urls.py
  notes/views.py
  notesapp/views.py
  static/javascript/authenticated.js
  static/javascript/script.js
  templates/notesapp/index.html
  templates/notesapp/main.html
Labels: SWOC, ADVANCE

#51 Added the filter feature
  MyNotepad/settings.py
  notes/migrations/0001_initial.py
  notes/models.py
  notes/views.py
  static/css/style.css
  static/javascript/authenticated.js
  templates/notesapp/main.html
Labels: SWOC, ADVANCE

#55 Implement autosave functionality
  static/javascript/authenticated.js
  static/javascript/autosave.js
  templates/notesapp/index.html
  templates/notesapp/main.html
Labels: SWOC, ADVANCE

#56 Fixed bug in requirements.txt
  requirements.txt
Labels: SWOC, BEGINNER

#66 Add Forgot Password Functionality #18
  MyNotepad/urls.py
  accounts/urls.py
  accounts/views.py
  static/css/style.css
  templates/notesapp/login.html
  templates/notesapp/password_reset.html
  templates/notesapp/reset_password.html
Labels: IWOC2025, Hard
