Repository ygowthamr/WhitePaper, pull requests merged in 2025-08, with the labels that each got.

#182 refactor: Standardize Static File References & Consolidate JS
  .gitattributes
  MyNotepad/urls.py
  README.md
  accounts/urls.py
  accounts/views.py
  index.html
  notes/migrations/0002_sharednotepermission.py
  notesapp/views.py
  requirements.txt
  requirements_clean.txt
  requirements_dev.txt
  static/javascript/Theme.js
  templates/notesapp/index.html
  templates/notesapp/login.html
  templates/notesapp/main.html
  templates/notesapp/password_reset.html
  templates/notesapp/reset_password.html
  templates/notesapp/signup.html
Labels: gssoc2025, Level 3

#166 Contributions - Support Pages
  index.html
  notesapp/urls.py
  notesapp/views.py
  templates/notesapp/faq.html
  templates/notesapp/index.html
  templates/notesapp/login.html
  templates/notesapp/main.html
  templates/notesapp/password_reset.html
  templates/notesapp/privacy_policy.html
  templates/notesapp/reset_password.html
  templates/notesapp/signup.html
  templates/notesapp/terms_conditions.html
Labels: gssoc2025

#175 Fix: Added tooltips and inline heading support (#164)
  static/javascript/script.js
Labels: gssoc2025, Level 2

#199 Add Standard CSS Property For Compatibility And Updating The Frontend Closes #200
  static/css/style.css
  static/javascript/script.js
  templates/notesapp/main.html
  templates/notesapp/password_reset.html
  templates/notesapp/reset_password.html
Labels: gssoc2025, Level 2, reviewed-needs-update

#209 Notification popup feature for note reminders (Closes #208)
  notes/forms.py
  notes/migrations/0003_tag_created_at_tag_reminder_datetime_and_more.py
  notes/migrations/0004_remove_tag_created_at_remove_tag_reminder_datetime_and_more.py
  notes/migrations/0005_alter_sharednotepermission_note_alter_tag_note.py
  notes/models.py
  notes/views.py
  notesapp/admin.py
  notesapp/migrations/0003_text_reminder_at_text_reminder_notified.py
  notesapp/migrations/0004_note.py
  notesapp/migrations/0005_delete_text.py
  notesapp/models.py
  notesapp/views.py
  static/javascript/authenticated.js
  templates/notesapp/main.html
Labels: gssoc2025, Level 3
